### ISSUE TITLE
tried to update eit popped up a window in infine loop, Uninstalled now gives new error

### ISSUE THREAD

**Issue by Advancedmart** [shopgoodwill-auction-sniper/shopgoodwill-bid-sniper#41]
![Screenshot 2024-09-14 161404](https://github.com/user-attachments/assets/e27da3f9-34cd-4abd-99ac-cd4b8c3dd2a5)
loop. 

uninstall now says. 
![errorScreenshot 2024-09-14 214239](https://github.com/user-attachments/assets/bdafcf52-b028-46b7-a635-e1cdb971d3bf)

**Comment by shopgoodwill-auction-sniper** [comment]
try exiting the program completely, and ensure it is not running in the system tray, and restart your computer to ensure no locked files are present and then copy the install/update command again from our homepage at Snipeable.com and execute in your powershell app, here is a 1 minute video on how to do that on Windows if you need it:

https://www.youtube.com/watch?v=MR4wrGBBgfM

**Comment by Advancedmart** [comment]
Still gives this error.  
![Error2Screenshot 2024-09-15 234608](https://github.com/user-attachments/assets/dceab80b-7300-4ec5-93b5-22f032235649)

**Comment by shopgoodwill-auction-sniper** [comment]
Are you using Windows 10 or 11?

**Comment by shopgoodwill-auction-sniper** [comment]
Please try opening your Powershell app as administrator by right clicking on the Poweshell app icon instead of left clicking on it and then click "Run as Administrator" and then copy/paste the Bid Sniper install/update command from our homepage at Snipeable.com into that Powershell app window and hit enter on your keyboard to execute that command and that should resolve the error you are experiencing.

Please let us know if we can be of further assistance.

Best regards,
Customer Service
Snipeable.com

**Comment by Advancedmart** [comment]
Ok log into shop goodwill account and seems to work, says snipped on auction. But of course it did not bid at all according to bidding history. So the new version still does not work.  I used up two snipes so far with zero results.  it does not bid. 


![biddinghistory](https://github.com/user-attachments/assets/e5080900-e866-479a-bc21-f677c1678f38)
![Snipe](https://github.com/user-attachments/assets/62647b40-f306-4a28-afaa-3f6bcc0176f4)

**Comment by shopgoodwill-auction-sniper** [comment]
Are you on Windows 10 or 11?

**Comment by Advancedmart** [comment]
Im on 10, it kinda works now, because I logged into shopgoodwill
on chrome first, but it still doesn't snipe even though it says it did.

**Comment by shopgoodwill-auction-sniper** [comment]
Can you login to the shopgoodwill website on your regular web browser and try to place a bid there to ensure there are no blockages on your bidding abilities and if all is ok there perhaps we can increase the snipe time by another half second till it works for you as well, we do have other users it does work for so I think it might have something to do with your computer speed or internet but first please check the shopgoodwill website and place a manual bid there to ensure there are no disruptions occurring there and let us know the results...

Thank you,
Technical Support 
Snipeable.com

**Comment by shopgoodwill-auction-sniper** [comment]
Ok, we have released a new update version 24.09.18.0548 for Windows that slightly increases the sniping timer, the reason we don't have a setting for the sniping timer is because it's a rhetorical setting, everyone would want the sniping timer to be as close to the end of the auction as possible, so that is why we don't have that setting, as more settings are overwhelming for users, so we design our apps to be auto-setting basically. Anyway, you can update to the latest version of Bid Sniper by running the install/update command on our homepage again at Snipeable.com but please don't forget to also launch your Powershell terminal as administrator in your case because your computer seems to have stricter security restrictions than most.

Please let us know if you need further assistance!

Best regards,
Technical Support
Snipeable.com

**Comment by Advancedmart** [comment]
I just tried again and still doesn't work.   winning bid
BidderBid AmountHigh BidderItem PriceTime of bid
f****o $12.99 f****o $12.99 09/19/2024 06:11:46 PM
Sniper says snipped. but it never showed as bid.

**Comment by shopgoodwill-auction-sniper** [comment]
Can you tell me the version you are using by going to the File menu up at the top of the window and clicking the about menu item?

**Comment by shopgoodwill-auction-sniper** [comment]
Can you tell me the version you are using by going to the File menu up at the top of the window and clicking the about menu, and also did you try placing a manual bid on an item on the ShopGoodwill website to ensure there are no blockages on your bidding capabilities coming directly from the website like we requested from you before?

**Comment by Advancedmart** [comment]
version 24.09.18.0548     I have placed bids since then manually.

**Comment by shopgoodwill-auction-sniper** [comment]
We have made a few more changes which may solve the issue, please update to the latest version by running the install/update command on our homepage again at Snipeable.com the latest version is now version 24.09.20.0641

Please let us know if the problem still persists after updating and we will refactor the sniping logic further...

Best regards,
Technical Support
Snipeable.com

**Comment by shopgoodwill-auction-sniper** [comment]
Hi AdvancedMart,

We are glad to announce that today we have released a new update version 24.09.22.1154 which resolves the issues you were experiencing by completely refactoring the sniping logic. 

You can update/install the latest version by going to our homepage at Snipeable.com and running the install/update command again.

That's all, you will 100% guaranteed see success with this new version, also this new version states if you won or lost the auction too and even provides an explanation in either case, instead of just stating "Sniped!" like the old version did, so we have completely refined the sniping process for your enjoyment!

Please let us know if we can be of further assistance.

Best regards,
Technical Support
Snipeable.com
